version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped